name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Enable corepack and setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Add pnpm to PATH
        run: echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Run lint
        run: pnpm lint
